version: '3'

services:
  speed:
    image: speed
    build: .   
    ports:
      - 3333:3333
    links: 
      - db
    depends_on:
      - db
    networks:
      - speed-network

  db:
    image: postgres
    environment:
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_DATABASE}
    ports:
      - '${DB_PORT}:${DB_PORT}'
    networks:
      - speed-network

  pg-admin:
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: "dev@speedsul.com"
      PGADMIN_DEFAULT_PASSWORD: "123456"
    ports:
      - "80:80"
    depends_on:
      - db
    networks:
      - speed-network

networks:
  speed-network:
    driver: bridge

