version: '3'

services:
  web-speed-api:
    build: .
    ports:
    - '${PORT}:${PORT}'
    depends_on:
      - db
    networks:
      - speed-network
    volumes:
    - .:/app
  db:
    image: postgres
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_DATABASE}
    ports:
      - '${DB_PORT}:${DB_PORT}' 
    networks:
      - speed-network
      
  pgadmin:
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD}
    ports:
      - "80:80"
    depends_on:
      - db
    networks:
      - speed-network

networks: 
  speed-network: